# Generated by Django 4.1.6 on 2023-02-13 16:17

import cloud.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='имя пользователя')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='IP-адрес :')),
                ('browser', models.CharField(max_length=200, verbose_name='браузер')),
                ('os', models.CharField(max_length=30, verbose_name='операционная система')),
                ('action', models.CharField(choices=[('0', 'войти'), ('1', 'опубликовывать'), ('2', 'Ошибка входа')], max_length=1, verbose_name='действия')),
                ('msg', models.CharField(max_length=100, verbose_name='данные')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='время')),
            ],
            options={
                'verbose_name': 'Журнал посещений пользователя',
                'verbose_name_plural': 'Журнал посещений пользователя',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('0', 'Жен'), ('1', 'Муж')], max_length=1, verbose_name='пол')),
                ('avatar', models.ImageField(default='default/avatar.svg', upload_to=cloud.utils.get_image_path, verbose_name='аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профиль пользователя',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('file_name', models.CharField(max_length=70, verbose_name='название файла')),
                ('path_to_the_file', models.CharField(max_length=50, unique=True, verbose_name='путь к файлу')),
                ('size', models.IntegerField(null=True, verbose_name='размер файла')),
                ('upload_date', models.DateField(auto_now_add=True, null=True, verbose_name='дата загрузки')),
                ('last_download_date', models.DateField(null=True, verbose_name='дата скачивания')),
                ('comment', models.TextField(max_length=100, null=True, verbose_name='комментарии')),
                ('download_link', models.CharField(default=cloud.utils.get_download_link, max_length=50, null=True, verbose_name='ссылка для скачивания')),
                ('file', models.FileField(blank=True, upload_to=cloud.utils.get_file_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
